import { fromJS } from "immutable";
export const language = fromJS({
  "zh-cn": {
    loader: {
      title: `正在载入中`,
      verificationTitle: `认证失效`,
      verification: `帐号认证已失效，请关闭页面`,
    },
    header: {
      title: `游戏纪录`,
    },
    timeZone: [
      { value: `0`, label: `美东时区` },
      { value: `12`, label: `北京时区` },
      { value: `4`, label: `伦敦时区` },
    ],
    cusDate: [
      { value: 0, label: `自订` },
      { value: 1, label: `前一天` },
      { value: 2, label: `前二天` },
      { value: 3, label: `前三天` },
      { value: 4, label: `前四天` },
      { value: 5, label: `前五天` },
      { value: 6, label: `前六天` },
    ],
    alert: {
      TZchange: `切换时区成功`,
      busy: `操作太频繁，请稍后`,
    },
    dataList: {
      // button:`点击详情`,
      freegame: `免费游戏`,
      singlerowbet: `再旋转`,
      bonus: `红利游戏`,
      // noMoreData:`没有更多了`,
      norecord: `没有历史纪录`,
    },
    headerList: [
      {
        type: "default",
        name: "默认",
      },
      {
        type: "isWin",
        name: "中奖",
      },
      {
        type: "isLose",
        name: "未中奖",
      },
    ],
    beforeThirty: `前30分`,
    today: `今天`,
    customized: `自订`,
    singleSearch: `单号搜索`,
    recordSearch: `纪录搜索`,
    dateSearch: `日期搜索：`,
    numberSearch: `单号搜索 (7天內)：`,
    btnSearch: `搜索`,
    searchPlaceholder: `请输入单号...`,
    backHome: `回首页`,
    norecord: `空空如也`,
    norecordSub: `找不着「|」这笔资料`,
  },
  en: {
    loader: {
      title: `Loading`,
      verificationTitle: `Invalid Verification`,
      verification: `Account verification is invalid, please close the page.`,
    },
    header: {
      title: `Game History`,
    },
    timeZone: [
      { value: `0`, label: `North American Eastern` },
      { value: `12`, label: `Beijing` },
      { value: `4`, label: `London` },
    ],
    cusDate: [
      { value: 0, label: `Customize` },
      { value: 1, label: `the day before` },
      { value: 2, label: `2 days ago` },
      { value: 3, label: `3 days ago` },
      { value: 4, label: `4 days ago` },
      { value: 5, label: `5 days ago` },
      { value: 6, label: `6 days ago` },
    ],
    alert: {
      TZchange: `Switch Time Zone Successfully.`,
      busy: `Server too busy, please wait.`,
    },
    dataList: {
      // button:`Detail`,
      freegame: `Free Game`,
      singlerowbet: `Respin`,
      bonus: `Bonus Game`,
      // noMoreData:`There is No More`,
      norecord: `No Game History`,
    },
    headerList: [
      {
        type: "default",
        name: "Default",
      },
      {
        type: "isWin",
        name: "Winning",
      },
      {
        type: "isLose",
        name: "Not Winning",
      },
    ],
    beforeThirty: `Pre 30 Minutes`,
    today: `Today`,
    customized: `Customize`,
    singleSearch: `Order History`,
    recordSearch: `Record Search`,
    dateSearch: `Date：`,
    numberSearch: `Order History (Within 7 Days)：`,
    btnSearch: `Search`,
    searchPlaceholder: `Please Enter Order No. ...`,
    backHome: `Home`,
    norecord: `No Data`,
    norecordSub: `Record「|」Is Not Found.`,
  },
  th: {
    loader: {
      title: `กำลังโหลด`,
      verificationTitle: `การยืนยันไม่ถูกต้อง`,
      verification: `การยืนยันบัญชีไม่ถูกต้อง โปรดปิดหน้า`,
    },
    header: {
      title: `ประวัติเกม`,
    },
    timeZone: [
      { value: `0`, label: `อเมริกาตะวันออก` },
      { value: `12`, label: `ปักกิ่ง` },
      { value: `4`, label: `ลอนดอน` },
    ],
    cusDate: [
      { value: 0, label: `ปรับแต่ง` },
      { value: 1, label: `วันก่อนหน้านี้` },
      { value: 2, label: `2วันที่แล้ว` },
      { value: 3, label: `3วันที่แล้ว` },
      { value: 4, label: `4วันที่แล้ว` },
      { value: 5, label: `5วันที่แล้ว` },
      { value: 6, label: `6วันที่แล้ว` },
    ],
    alert: {
      TZchange: `โซนเวลาสลับสำเร็จ`,
      busy: `เซิร์ฟเวอร์ไม่ว่างดปรดรอสักครู่`,
    },
    dataList: {
      // button:`Detail`,
      freegame: `เกมฟรี`,
      singlerowbet: `หมุนอีกครั้ง`,
      bonus: `เกมโบนัส`,
      // noMoreData:`There is No More`,
      norecord: `ไม่มีประวัติเกม`,
    },
    headerList: [
      {
        type: "default",
        name: "ค่าเร่มต้น",
      },
      {
        type: "isWin",
        name: "ชนะ",
      },
      {
        type: "isLose",
        name: "ไม่ชนะ",
      },
    ],
    beforeThirty: `ก่อน 30 นาที`,
    today: `วันนี้`,
    customized: `ปรับแต่ง`,
    singleSearch: `หมายเลขสั่งซื้อ`,
    recordSearch: `บันทึกการค้นหา`,
    dateSearch: `วันที่：`,
    numberSearch: `ประวัติการสั่งซื้อ(ภายใน 7 วัน)：`,
    btnSearch: `ค้นหา`,
    searchPlaceholder: `กรุณากรอกลำดับที่`,
    backHome: `บ้าน`,
    norecord: `ไม่มีข้อมูล`,
    norecordSub: `ไม่พบบันทึก「|」เซิร์ฟเวอร์ไม่ว่างดปรดรอสักครู่การยืนยันไม่ถูกต้อง`,
  },
  vn: {
    loader: {
      title: `Đang tải`,
      verificationTitle: `Chứng nhận vô hiệu`,
      verification: `Chứng nhận của tài khoản đã vô hiệu, vui lòng đóng trang`,
    },
    header: {
      title: `Lịch sử trò chơi`,
    },
    timeZone: [
      { value: `0`, label: `Múi giờ Mỹ Đông` },
      { value: `12`, label: `Múi giờ Bắc Kinh` },
      { value: `4`, label: `Múi giờ Luân Đôn` },
    ],
    cusDate: [
      { value: 0, label: `Tự đặt` },
      { value: 1, label: `Hôm qua` },
      { value: 2, label: `2 ngày trước` },
      { value: 3, label: `3 ngày trước` },
      { value: 4, label: `4 ngày trước` },
      { value: 5, label: `5 ngày trước` },
      { value: 6, label: `6 ngày trước` },
    ],
    alert: {
      TZchange: `Chuyển đổi múi giờ thành công`,
      busy: `Thao tác quá nhiều lần, vui lòng chờ đợi`,
    },
    dataList: {
      // button:`Detail`,
      freegame: `Free Game`,
      singlerowbet: `Respin`,
      bonus: `Bonus Game`,
      // noMoreData:`There is No More`,
      norecord: `Không có lịch sử ghi chép`,
    },
    headerList: [
      {
        type: "default",
        name: "Mặc định",
      },
      {
        type: "isWin",
        name: "Trúng thưởng",
      },
      {
        type: "isLose",
        name: "Khu đặt cược",
      },
    ],
    beforeThirty: `Trước 30 phút`,
    today: `Hôm nay`,
    customized: `Tự đặt`,
    singleSearch: `Tìm kiếm số đơn`,
    recordSearch: `Lịch sử tìm kiếm`,
    dateSearch: `Ngày tìm kiếm：`,
    numberSearch: `Tìm kiếm số đơn (Trong vòng 7 ngày)：`,
    btnSearch: `Tìm kiếm`,
    searchPlaceholder: `Vui lòng nhập số đơn`,
    backHome: `Về trang chủ`,
    norecord: `Không có ghi chép`,
    norecordSub: `Không tìm thấy dữ liệu「|」này`,
  },
});
